spring:
  datasource:
    username: root
    password: AshokIT@123
    url: jdbc:mysql://localhost:3306/jrtp
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc: 
    view:
      prefix: /pages/
      suffix: .jsp
      
   
  mail:
    host: smtp.gmail.com
    port: 587
    username: surajs07711@gmail.com 
    password: lpyziramikpahmsu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    
      
          
      
      
      
      
      
      
      
      
      
  
